### ISSUE TITLE
Springs.ErrorReport.Parse

### ISSUE THREAD

**Issue by indiebimbo** [dimven/SpringNodes#19] opened 2016-09-19 18:21 UTC
Everything's comin' up null!

**Comment by dimven** [comment] 2016-09-20 01:49
Hi,

Could you share the error report? That might help find the problem. Here's some of the reasons that it might be failing:
- You're running on a localized (non-english) version of Revit. This popped up in a French version of Revit, where the error report format is in french and can not be parsed with the default settings.
- You're feeding in the error report from a different project file. I do that a lot when I'm managing a project with a lot of linked files. The ids of the elements do not exist in the current project and fail to be selected. Try feeding in a "False" boolean into the "fetch elements" input and see if you can get any id strings.

![dynamosandbox_2016-09-20_09-50-40](https://cloud.githubusercontent.com/assets/7148394/18654983/c828b526-7f17-11e6-8850-6e3987b7365e.png)
- The elements in the report might have been deleted or their ids have changed. This is common in federated models, where creating a new central or local file can change some of the element ids.

**Comment by indiebimbo** [comment] 2016-09-23 20:46
Hi,

Thanks for your response. I am running an english version of Revit, with a false boolean input, and I have exported the error message from the same model which I am working in. I thought perhaps the error might have been because my error html file and Revit model were on separate local drives, but that has not resolved the issue. Image is added below:

![image](https://cloud.githubusercontent.com/assets/22303034/18800826/2b887d94-81ad-11e6-984b-9fe2d2a2f6a4.png)

**Comment by indiebimbo** [comment] 2016-09-23 20:48
Error Report (renamed from example above):
[Error Report temp.zip](https://github.com/dimven/SpringNodes/files/490649/Error.Report.temp.zip)

**Comment by dimven** [comment] 2016-09-24 02:46
Works as expected on my side:
![dynamosandbox_2016-09-24_10-45-48](https://cloud.githubusercontent.com/assets/7148394/18805575/1a9ed680-8244-11e6-9b27-cb6e2687cea8.png)

Could you try deleting and re-downloading spring nodes?

**Comment by huvec** [comment] 2016-10-03 22:25
Hi There i am getting the same error as well. II am using spring nodes 100.0.1. I have deleted and reinstalled the package.

Any help appreciated.
Thanks

![image](https://cloud.githubusercontent.com/assets/16100298/19056359/37176654-8a25-11e6-9b21-069d38afe773.png)

**Comment by dimven** [comment] 2016-10-03 23:08
Could you edit the custom node, copy the python script, paste it on the main canvas and run it with the same inputs? That will give me some more info to work with

**Comment by huvec** [comment] 2016-10-04 00:10
Hi,
i have tryed a few things.. seem it appears the file path node may be
different between 0.92 and 1.1.

I changed it and it works now.

[image: Inline image 1]

Cheers,

Jasper Wong
m.+642108252763

**Comment by huvec** [comment] 2016-10-04 02:45
Hi there,
I thought I solved it. but here is the error messages coming through..
[image: Inline image 1]

Cheers,

Jasper Wong
m.+642108252763

**Comment by dimven** [comment] 2016-10-04 10:51
Hi @huvec, your image seems to be missing.

**Comment by indiebimbo** [comment] 2016-10-04 15:46
Hi, copied the code into a new code block, and it displays the error "Error: openparen expected"
![2016-10-04-springnodes-error_parse-code_paste](https://cloud.githubusercontent.com/assets/22303034/19081365/fd9d20be-8a27-11e6-9275-7e38333a6635.jpg)

**Comment by huvec** [comment] 2016-10-04 23:22
Hi There , image attached for your info

[image: Inline image 1]

Cheers,

Jasper Wong
m.+642108252763

**Comment by dimven** [comment] 2016-10-05 13:15
@huvec the image still seems to be missing...

@indiebimbo Sorry I meant you need to copy the python script node from inside the CN, not the content of the script, like so:

![revit_2016-10-05_21-14-00](https://cloud.githubusercontent.com/assets/7148394/19114496/c8adb250-8b40-11e6-985c-bd0488c46cde.png)

**Comment by indiebimbo** [comment] 2016-10-05 18:04
Works this way, but not back in the code.
![2016-10-05-springnodes-error_parse-code_paste 2](https://cloud.githubusercontent.com/assets/22303034/19125187/1694335a-8b04-11e6-8172-936ccf26edec.JPG)

**Comment by indiebimbo** [comment] 2016-10-05 18:11
Copy pasting it back into the main canvas gives me this:
![2016-10-05-springnodes-error_parse-code_paste 3](https://cloud.githubusercontent.com/assets/22303034/19125577/a24f1ea4-8b05-11e6-9e88-7c43128ea412.jpg)

**Comment by andydandy74** [comment] 2016-10-05 18:44
@indiebimbo  - Try getting rid of the whitespace in your filename.

**Comment by andydandy74** [comment] 2016-10-05 18:47
@dimven - I think I've seen this happen recently in another context, I think it was with some BumbleBee nodes failing after I upgraded Dynamo. Almost looks like Dynamo's filepath encoding may have changed ?!?

**Comment by indiebimbo** [comment] 2016-10-05 19:38
@andydandy74 That did the trick, thank you!

**Comment by huvec** [comment] 2016-10-05 23:28
No spaces in the file path works a treat.
thanks

Cheers,

Jasper Wong
m.+642108252763

**Comment by dimven** [comment] 2016-10-06 01:18
@andydandy74 yes... The recent changes to the file path node do some real shenanigans... It serializes and de-serializes the path string to and from XML and that seems to be the root cause:

https://github.com/DynamoDS/Dynamo/commit/fe2747501285c11f010767285ccfedd3724087fd#diff-61687cff109bf8960684cdfec79bde79R75

I think that this could have been handled a lot more gracefully with an instance property? might need to raise this issue with the Dynamo Dev team.

**Comment by andydandy74** [comment] 2016-10-06 06:42
@dimven - No need. I just tested this with 1.2 stable and it now works as expected again. You can close this one. 
BTW: You should add an issue template to your repo. ;-)

**Closed as completed** 2016-11-06 02:03 UTC
Labels: cannot replicate
