### ISSUE TITLE
Mesh.ToPolysurface slow after update

### ISSUE THREAD

**Issue by josols** [dimven/SpringNodes#36] opened 2017-11-11 05:24 UTC
Can’t pinpoint at which update it happens, but after the introduction of the mergeAll input scripts are slowed down significantly or even freezing everything up. Any idea?

**Comment by dimven** [comment] 2017-11-11 12:21
Hi Jos,

That's really strange - there have been no major changes in ages. The only recent change as you noted was the merge all option (which is off by default) and that's literally one line of code at the end:
> if IN[1]:
>    OUT = PolySurface.ByJoinedSurfaces(OUT)

Has anything else changed in your workflow or your input data?

**Comment by josols** [comment] 2017-11-11 13:26
No, and that’s the weird part of it.. I had a script, unfortunately not at a PC right now so I can share, which suddenly took around 20 minutes to run compared to 6-7 minutes before, and the only difference was the version of spring nodes. I have since tested others cripts as well and it is the same with all of them. Some are not even running through at all and, as stated, freeze everything up.. I’ll do some more checks when I’m at a PC again.

**Comment by dimven** [comment] 2017-12-13 09:27
Did a quick test between Revit 2016 R2 U7 (basic sample model's topo):

![revit_2017-12-13_17-14-55](https://user-images.githubusercontent.com/7148394/33930960-983f07b0-e029-11e7-99a7-f62f252901b7.png)

Revit 2017.2 : 

![image](https://user-images.githubusercontent.com/7148394/33931361-b808f2d0-e02a-11e7-9529-3fc02511b43d.png)

and Revit 2018.0 : 

![revit_2017-12-13_17-16-19](https://user-images.githubusercontent.com/7148394/33931082-ef3021d0-e029-11e7-83fe-5443c28b31b4.png)

and got pretty much identical timings of about 1.5 ~ 2 s for all three

**Comment by dimven** [comment] 2018-02-07 02:34
Since we concluded the problem is in the ASM surface kernel, I'll close this for now.

**Closed as completed by dimven** 2018-02-07 02:34 UTC
